spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  datasource:
    url: jdbc:mysql://localhost:3306/otr?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Kathmandu&useLegacyDatetimeCode=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

app:
  frontEnd:
    endPoint: http://localhost:3000
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 604800000
  defaults:
    user:
      name: Umesh Giri
      email: umeshgiriplay@gmail.com
      password: XDCFVGBH56789@@?????

server:
  port: 8080

logging:
  file:
    clean-history-on-start: true
    name: otr.log